# Generated by Django 5.2.4 on 2025-07-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1_name', models.CharField(max_length=255)),
                ('file2_name', models.CharField(max_length=255)),
                ('summary', models.JSONField()),
                ('diff', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
