# Generated by Django 5.2.4 on 2025-07-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonhistory',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='comparisonhistory',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
